action.auto_create_index: false
indices.cache.cleanup_interval: 1h
network.host: "0.0.0.0"
transport.host: "0.0.0.0"
http.port: 9201
node.master: false
node.data: true
node.name: es-data-01
cluster.name: es-cluster-01
discovery.zen.ping.unicast.hosts:
 - es-master-01
 - es-data-01