version: '3'
volumes:
  elasticsearch:
services:
  elasticsearch : 
    image:  elasticsearch:5.5.2
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ../config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
    - "9200:9200"
